FROM node:24.17.0-alpine

ENV NODE_ENV=development

RUN mkdir -p /app \
    && chown node:node /app \
    && corepack enable \
    && corepack prepare pnpm@11.0.5 --activate

USER node
WORKDIR /app

EXPOSE 3000

CMD [ "pnpm", "dev" ]